version: '3.8'

services:
  # 服务1：你的 MySQL 数据库
  db:
    image: mysql:8.0
    container_name: docpilot_mysql
    restart: always
    environment:
      # 这里设置数据库的 Root 密码，要和你在后端代码里连数据库的密码一致！
      MYSQL_ROOT_PASSWORD: 123456  
      MYSQL_DATABASE: docpilot
    ports:
      - "3307:3306"
    volumes:
      # 数据卷挂载：保证即使容器被删了，你的数据库数据依然保存在电脑的 mysql_data 文件夹里
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456"]
      interval: 5s
      timeout: 5s
      retries: 10
  # 服务2：你的 FastAPI 后端
  web:
    # build: 
    #   context: ./backend
    image: ccr.ccs.tencentyun.com/docpilot/web_image:v1
    container_name: docpilot_fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_URL=mysql://root:123456@db:3306/docpilot
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 服务3：Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: docpilot_redis
    restart: always
    ports:
      - "6369:6379"
    # 开启redis-AOF，保证数据持久化
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data

  # 服务4：前端
  frontend:
    # build:
    #   context: ./frontend
    image: ccr.ccs.tencentyun.com/docpilot/frontend_image:v1
    container_name: docpilot_frontend
    restart: always
    ports:
      - "8401:8501"
    environment:
      - BACKEND_URL=http://web:8000
    depends_on:
      web:
        condition: service_started